libnxter: Motor.nxc File Reference
Motor.nxc File Reference
Motor control implementation.
#include "PID.nxc"
#include "Screen.nxc"
Functions
void MotorStart (int motor, int power)
Starts the given motor with the given power.
void MotorStop (int motor)
Stops the given motor.
void MotorSetPower (int motor, int power)
Set the power of given motor.
void MotorStartSync (int motor1, int motor2, int power)
Starts the given 2 motors in synchronous mode with with the given initial power.
void MotorStopSync (int motor1, int motor2)
Stops the given two motor pair.
void MotorSetPowerSync (int motor1, int motor2, int power)
Sets the power of the given motor pair.
void MotorSetTurnRatio (int motor1, int motor2, int turnRatio)
Sets the turn ratio of the given motor pair running in synchronous mode.
void MotorSetTurnRatioPower (int motor1, int motor2, int turnRatio, int power)
Sets the turn ratio and power at the same time of the given motor pair running in synchronous mode.
int MotorRotateAngle (int motor, int power, long angle, long PValue, long IValue, long DValue)
Rotates the given motor by given angle using the specified P, I and D gain values. The power is the maximum power to use for rotation.
int MotorRotateAngleSync (int motor1, int motor2, int power, long angle, long PValue, long IValue, long DValue)
Rotates the given pair of motors synchromously (that is they rotate at the same pace) by given angle using the specified P, I and D gain values. The power is the maximum power to use for rotation.
int MotorRotateAngleDiff (int motor1, int motor2, int power, long angle, long PValue, long IValue, long DValue)
Rotates the given pair of motors differentially (that is they rotate at the same pace in opposite direction) by given angle using the specified P, I and D gain values. The power is the maximum power to use for rotation.
Detailed Description
Motor control implementation.
Definition in file Motor.nxc.
Function Documentation
void MotorStartSync (int motor1, int motor2, int power) [inline]
Starts the given 2 motors in synchronous mode with with the given initial power.
Synchronous mode keeps the two motors go with the same rotation counts -- effectively keeping the drive go straight line.
Definition at line 71 of file Motor.nxc.
Referenced by MotorRotateAngleDiff(), MotorRotateAngleSync(), VehicleAddNavPoint(), VehicleAddNavPoints(), and VehicleContinue().